[package]
name    = "benchmark"
version = "1.0.0"
edition = "2021"
license = "PolyForm-Noncommercial-1.0.0"

[dependencies]
bitvec = { workspace = true }
clap = { workspace = true }
core = { workspace = true }
error_correction = { path = "../error-correction-cascade/", package="ec_cascade"}
rand = { workspace = true }
rayon = { workspace = true }
