[package]
name = "benchmark"
version = "1.0.0"
edition = "2021"

[dependencies]
core = { path = "../core/" }
error_correction = { path = "../error-correction-cascade/", package="ec_cascade"}
bitvec = { version = "1.0.1", features = ["serde", "std"] }
rand = "0.8.5"
rayon = "1.10.0"
clap = { version = "4.5.4", features = ["derive", "wrap_help"] }
