[package]
name    = "ec_simcommsys"
version = "1.0.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"

[dependencies]
ppaas_core = { workspace = true, features = [ "reqwest", "ec_simcommsys" ] }
reqwest = { workspace = true }
serde = { workspace = true, features = [ "rc" ] }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }
bitvec = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
