[module]
uuid             = "00000000-0000-0000-0000-00000000000a"
error_correction = ['Cascade', 'LDPC']
peer_addr        = "127.0.0.1:61000"
qkd_addr         = "127.0.0.1:60000"
root_cert        = "./certificates/root.pem"
module_cert      = "./certificates/module.pem"
logfile          = "app_alice.json"
logfile_level    = "INFO"
stdout_level     = "INFO"

[[peers]]
uuid = "00000000-0000-0000-0000-00000000000b"
addr = '127.0.0.1:61001'

[[peers.qkd]]
local = "00000000-0000-0000-0000-0000000000ab"
remote = "00000000-0000-0000-0000-0000000000ba"

[simcommsys]
base_url = "http://localhost:8000"

[[simcommsys.ldpc_codes]]
id = "aegle-alice-6-4"
min_ber = 0.0
max_ber = 0.1
block_length = 6

[simcommsys.ldpc_codes.matrix]
definition = [
    [0, 1, 1, 0, 0, 0],
    [1, 1, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 1],
]

[[simcommsys.ldpc_codes]]
id = "aegle-alice-15-10"
min_ber = 0.1
max_ber = 0.5
block_length = 15

[simcommsys.ldpc_codes.matrix]
definition = [
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
]
