[package]
name    = "aegle"
version = "1.0.0"
edition = "2021"
license = "PolyForm-Noncommercial-1.0.0"

[features]
default = ["ec_cascade"]
ec_cascade = ["dep:ec_cascade"]
ec_simcommsys = ["dep:ec_simcommsys", "core/ec_simcommsys"]

[dependencies]
bincode = { workspace = true }
bitvec = { workspace = true }
clap = { workspace = true }
core = { path = "../core/" }
ec_cascade = { path = "../error-correction-cascade", package = "ec_cascade", optional = true }
ec_simcommsys = { path = "../error-correction-simcommsys", package = "ec_simcommsys", optional = true }
p12-keystore = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rand = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
statrs = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
