[package]
name    = "aegle"
version = "1.0.0"
edition = "2021"
license = "PolyForm-Noncommercial-1.0.0"

[dependencies]
bincode = { workspace = true }
bitvec = { workspace = true }
clap = { workspace = true }
core = { path = "../core/" }
error_correction = { path = "../error-correction-cascade", package = "ec_cascade" }
p12-keystore = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rand = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
statrs = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
